-- ============================================================================
--  KDN 수강생 프로젝트 통합 Supabase 셋업 스크립트  (하나의 파일)
--  대상 프로젝트: aebonlee's Project (공유)  ->  ref hcmgdztsgjvzcyxyayaj
--  사용법: Supabase Dashboard > SQL Editor > New query 에 전체 붙여넣고 Run
--
--  * 공유 프로젝트 충돌 방지를 위해 모든 객체에 kdnNN_ 접두사를 적용했습니다.
--  * 재실행 안전: 각 섹션이 DROP ... CASCADE 후 재생성합니다(기존 데이터 삭제됨).
--  * auth.users 트리거는 kdnNN_ 이름이라 운영(dreamitbiz) 트리거와 충돌하지 않습니다.
--
--  [중요] 각 앱이 이 테이블을 실제로 쓰려면 "앱 코드"도 같은 kdnNN_ 접두사를 써야 합니다.
--     - kdn01 / kdn02 / kdn03 / kdn06 : 코드 적용 완료 (배포됨)
--     - kdn20 / kdn22 / kdn28 / kdn29 : 코드 미적용 -> 요청 시 코드 수정·재배포 예정
-- ============================================================================

create extension if not exists "pgcrypto";

-- ============================================================================
-- kdn01  운세앱 게시판 (posts, board_comments)
-- ============================================================================
drop table if exists public.kdn01_board_comments cascade;
drop table if exists public.kdn01_posts cascade;

create table public.kdn01_posts (
  id uuid primary key default gen_random_uuid(),
  board text not null, title text not null, content text not null,
  author text not null, email text default '',
  created_at timestamptz default now(), view_count int default 0, comment_count int default 0
);
create table public.kdn01_board_comments (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.kdn01_posts(id) on delete cascade,
  author text not null, content text not null, created_at timestamptz default now()
);
create index if not exists idx_kdn01_posts_board   on public.kdn01_posts(board);
create index if not exists idx_kdn01_posts_created on public.kdn01_posts(created_at desc);
create index if not exists idx_kdn01_comments_post on public.kdn01_board_comments(post_id);
alter table public.kdn01_posts enable row level security;
alter table public.kdn01_board_comments enable row level security;
create policy "kdn01 read posts"    on public.kdn01_posts for select using (true);
create policy "kdn01 insert posts"  on public.kdn01_posts for insert with check (true);
create policy "kdn01 update posts"  on public.kdn01_posts for update using (true);
create policy "kdn01 read comments"   on public.kdn01_board_comments for select using (true);
create policy "kdn01 insert comments" on public.kdn01_board_comments for insert with check (true);

-- ============================================================================
-- kdn02  전력설비 점검 보고 (inspection_reports) + 샘플 데이터
-- ============================================================================
drop table if exists public.kdn02_inspection_reports cascade;
create table public.kdn02_inspection_reports (
  id bigint generated by default as identity primary key,
  equipment_id text not null default '-',
  equipment_name text not null,
  type text not null default '정기점검',
  inspector text not null,
  date date not null,
  result text not null default '이상없음',
  note text default '',
  created_at timestamptz default now()
);
alter table public.kdn02_inspection_reports enable row level security;
create policy "kdn02 allow_all" on public.kdn02_inspection_reports for all using (true) with check (true);
insert into public.kdn02_inspection_reports (equipment_id, equipment_name, type, inspector, date, result, note) values
('TR-001','주변압기 1호','정기점검','김철수','2026-05-20','이상없음','오일 샘플 채취, 권선온도 측정 완료'),
('GEN-002','발전기 2호','예방점검','이영희','2026-05-25','주의','베어링 교체 작업 진행 중'),
('CB-001','차단기 1번','동작시험','박대중','2026-05-21','이상없음','개폐 동작 확인, 접점 마모 미미'),
('MOT-001','펌프 모터 1','절연저항측정','최수진','2026-05-22','이상없음','절연저항 450M옴 측정, 양호'),
('CAB-001','154kV 케이블 1','부분방전측정','정대한','2026-05-15','요주의','부분방전 2.5pC 감지, 정밀진단 예약 필요'),
('DP-001','배전반 A-1','청소 및 점검','서지원','2026-05-23','이상없음','내부 청소, 단자 체결 확인');

-- ============================================================================
-- kdn03  취약점 진단 (assets, scans, fixes, notices, threats, resources)
-- ============================================================================
drop table if exists public.kdn03_scans cascade;
drop table if exists public.kdn03_fixes cascade;
drop table if exists public.kdn03_resources cascade;
drop table if exists public.kdn03_threats cascade;
drop table if exists public.kdn03_notices cascade;
drop table if exists public.kdn03_assets cascade;

create table public.kdn03_assets (
  id uuid primary key default gen_random_uuid(),
  hostname text not null, ip text default '', os_type text default '', os_version text default '',
  department text default '', "owner" text default '', location text default '', note text default '',
  created_at timestamptz not null default now()
);
create table public.kdn03_scans (
  id uuid primary key default gen_random_uuid(),
  asset_id uuid references public.kdn03_assets(id) on delete set null,
  hostname text not null, scan_date timestamptz not null, file_name text default '',
  uploaded_at timestamptz not null default now(), uploaded_by text default '',
  total int not null default 0, vuln_count int not null default 0, good_count int not null default 0,
  manual_count int not null default 0, score numeric(5,1) not null default 0,
  results jsonb not null default '[]'::jsonb
);
create table public.kdn03_fixes (
  id uuid primary key default gen_random_uuid(),
  asset_id uuid references public.kdn03_assets(id) on delete set null,
  hostname text not null, fix_date timestamptz not null, file_name text default '',
  uploaded_at timestamptz not null default now(), items_arg text default '',
  total int not null default 0, fixed_count int not null default 0, reported_count int not null default 0,
  manual_count int not null default 0, fail_count int not null default 0,
  items jsonb not null default '[]'::jsonb
);
create table public.kdn03_notices (
  id uuid primary key default gen_random_uuid(),
  category text not null default '일반', title text not null, body text default '',
  author text default '관리자', pinned boolean not null default false, views int not null default 0,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.kdn03_threats (
  id uuid primary key default gen_random_uuid(),
  title text not null, cve text default '', severity text not null default '중간',
  source text default '', source_url text default '', published_date text default '',
  tags jsonb not null default '[]'::jsonb, related_items jsonb not null default '[]'::jsonb,
  body text default '', author text default '관리자', views int not null default 0,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.kdn03_resources (
  id uuid primary key default gen_random_uuid(),
  category text not null default '가이드', title text not null, description text default '',
  file_name text default '', file_path text default '', file_url text default '',
  file_size bigint default 0, mime text default '', author text default '관리자',
  downloads int not null default 0,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.kdn03_assets    enable row level security;
alter table public.kdn03_scans     enable row level security;
alter table public.kdn03_fixes     enable row level security;
alter table public.kdn03_notices   enable row level security;
alter table public.kdn03_threats   enable row level security;
alter table public.kdn03_resources enable row level security;
create policy "kdn03 assets all"    on public.kdn03_assets    for all to authenticated using (true) with check (true);
create policy "kdn03 scans all"     on public.kdn03_scans     for all to authenticated using (true) with check (true);
create policy "kdn03 fixes all"     on public.kdn03_fixes     for all to authenticated using (true) with check (true);
create policy "kdn03 notices all"   on public.kdn03_notices   for all to authenticated using (true) with check (true);
create policy "kdn03 threats all"   on public.kdn03_threats   for all to authenticated using (true) with check (true);
create policy "kdn03 resources all" on public.kdn03_resources for all to authenticated using (true) with check (true);
insert into storage.buckets (id, name, public) values ('kdn03_resources','kdn03_resources',true) on conflict (id) do nothing;
drop policy if exists "kdn03 res storage read"   on storage.objects;
drop policy if exists "kdn03 res storage write"  on storage.objects;
drop policy if exists "kdn03 res storage delete" on storage.objects;
create policy "kdn03 res storage read"   on storage.objects for select using (bucket_id = 'kdn03_resources');
create policy "kdn03 res storage write"  on storage.objects for insert to authenticated with check (bucket_id = 'kdn03_resources');
create policy "kdn03 res storage delete" on storage.objects for delete to authenticated using (bucket_id = 'kdn03_resources');

-- ============================================================================
-- kdn06  Real Zero SNS (feed_items + increment_cheer + feed-images 버킷)
-- ============================================================================
drop table if exists public.kdn06_feed_items cascade;
create table public.kdn06_feed_items (
  id uuid default gen_random_uuid() primary key,
  user_name text not null, user_handle text not null, avatar_url text,
  category text not null, image_url text, caption text not null,
  cheer_count integer default 0 not null, created_at timestamptz default now() not null
);
create index if not exists kdn06_feed_items_created_at_idx on public.kdn06_feed_items (created_at desc);
alter table public.kdn06_feed_items enable row level security;
create policy "kdn06 public_read"   on public.kdn06_feed_items for select using (true);
create policy "kdn06 public_insert" on public.kdn06_feed_items for insert with check (true);
create or replace function public.kdn06_increment_cheer(item_id uuid)
returns void language sql security definer set search_path = public as $$
  update public.kdn06_feed_items set cheer_count = cheer_count + 1 where id = item_id;
$$;
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('kdn06-feed-images','kdn06-feed-images',true,5242880,array['image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do nothing;
drop policy if exists "kdn06 image read"   on storage.objects;
drop policy if exists "kdn06 image insert" on storage.objects;
create policy "kdn06 image read"   on storage.objects for select using (bucket_id = 'kdn06-feed-images');
create policy "kdn06 image insert" on storage.objects for insert with check (bucket_id = 'kdn06-feed-images');

-- ============================================================================
-- kdn20  업무 일지 (projects, todos)
-- ============================================================================
drop table if exists public.kdn20_todos cascade;
drop table if exists public.kdn20_projects cascade;
create table public.kdn20_projects (
  id uuid primary key default gen_random_uuid(),
  name text not null, color text not null default '#3D6FE0',
  created_at timestamptz not null default now()
);
create table public.kdn20_todos (
  id uuid primary key default gen_random_uuid(),
  title text not null, completed boolean not null default false,
  category text not null default '업무' check (category in ('업무','개발','미팅','교육','기타')),
  description text, project_id uuid references public.kdn20_projects(id) on delete set null,
  due_date date, sort_order integer,
  created_at timestamptz not null default now(), completed_at timestamptz
);
create index if not exists idx_kdn20_todos_project on public.kdn20_todos (project_id);
alter table public.kdn20_projects enable row level security;
alter table public.kdn20_todos    enable row level security;
create policy "kdn20 proj auth" on public.kdn20_projects for all using (auth.role()='authenticated') with check (auth.role()='authenticated');
create policy "kdn20 todo auth" on public.kdn20_todos    for all using (auth.role()='authenticated') with check (auth.role()='authenticated');

-- ============================================================================
-- kdn22  취약점 진단 (kdn03와 동일 스키마, kdn22_ 접두사)
-- ============================================================================
drop table if exists public.kdn22_scans cascade;
drop table if exists public.kdn22_fixes cascade;
drop table if exists public.kdn22_resources cascade;
drop table if exists public.kdn22_threats cascade;
drop table if exists public.kdn22_notices cascade;
drop table if exists public.kdn22_assets cascade;
create table public.kdn22_assets (
  id uuid primary key default gen_random_uuid(),
  hostname text not null, ip text default '', os_type text default '', os_version text default '',
  department text default '', "owner" text default '', location text default '', note text default '',
  created_at timestamptz not null default now()
);
create table public.kdn22_scans (
  id uuid primary key default gen_random_uuid(),
  asset_id uuid references public.kdn22_assets(id) on delete set null,
  hostname text not null, scan_date timestamptz not null, file_name text default '',
  uploaded_at timestamptz not null default now(), uploaded_by text default '',
  total int not null default 0, vuln_count int not null default 0, good_count int not null default 0,
  manual_count int not null default 0, score numeric(5,1) not null default 0,
  results jsonb not null default '[]'::jsonb
);
create table public.kdn22_fixes (
  id uuid primary key default gen_random_uuid(),
  asset_id uuid references public.kdn22_assets(id) on delete set null,
  hostname text not null, fix_date timestamptz not null, file_name text default '',
  uploaded_at timestamptz not null default now(), items_arg text default '',
  total int not null default 0, fixed_count int not null default 0, reported_count int not null default 0,
  manual_count int not null default 0, fail_count int not null default 0,
  items jsonb not null default '[]'::jsonb
);
create table public.kdn22_notices (
  id uuid primary key default gen_random_uuid(),
  category text not null default '일반', title text not null, body text default '',
  author text default '관리자', pinned boolean not null default false, views int not null default 0,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.kdn22_threats (
  id uuid primary key default gen_random_uuid(),
  title text not null, cve text default '', severity text not null default '중간',
  source text default '', source_url text default '', published_date text default '',
  tags jsonb not null default '[]'::jsonb, related_items jsonb not null default '[]'::jsonb,
  body text default '', author text default '관리자', views int not null default 0,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.kdn22_resources (
  id uuid primary key default gen_random_uuid(),
  category text not null default '가이드', title text not null, description text default '',
  file_name text default '', file_path text default '', file_url text default '',
  file_size bigint default 0, mime text default '', author text default '관리자',
  downloads int not null default 0,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.kdn22_assets    enable row level security;
alter table public.kdn22_scans     enable row level security;
alter table public.kdn22_fixes     enable row level security;
alter table public.kdn22_notices   enable row level security;
alter table public.kdn22_threats   enable row level security;
alter table public.kdn22_resources enable row level security;
create policy "kdn22 assets all"    on public.kdn22_assets    for all to authenticated using (true) with check (true);
create policy "kdn22 scans all"     on public.kdn22_scans     for all to authenticated using (true) with check (true);
create policy "kdn22 fixes all"     on public.kdn22_fixes     for all to authenticated using (true) with check (true);
create policy "kdn22 notices all"   on public.kdn22_notices   for all to authenticated using (true) with check (true);
create policy "kdn22 threats all"   on public.kdn22_threats   for all to authenticated using (true) with check (true);
create policy "kdn22 resources all" on public.kdn22_resources for all to authenticated using (true) with check (true);
insert into storage.buckets (id, name, public) values ('kdn22_resources','kdn22_resources',true) on conflict (id) do nothing;
drop policy if exists "kdn22 res storage read"   on storage.objects;
drop policy if exists "kdn22 res storage write"  on storage.objects;
drop policy if exists "kdn22 res storage delete" on storage.objects;
create policy "kdn22 res storage read"   on storage.objects for select using (bucket_id = 'kdn22_resources');
create policy "kdn22 res storage write"  on storage.objects for insert to authenticated with check (bucket_id = 'kdn22_resources');
create policy "kdn22 res storage delete" on storage.objects for delete to authenticated using (bucket_id = 'kdn22_resources');

-- ============================================================================
-- kdn28  Worklog (report_summaries)  *members/projects/work_logs는 스키마 미제공
-- ============================================================================
drop table if exists public.kdn28_report_summaries cascade;
create table public.kdn28_report_summaries (
  id uuid primary key default gen_random_uuid(),
  project_key text not null, range text not null,
  start_date text not null, end_date text not null,
  content text not null, created_at timestamptz not null default now(),
  constraint kdn28_report_summaries_unique unique (project_key, range, start_date, end_date)
);
alter table public.kdn28_report_summaries enable row level security;
create policy "kdn28 reports all" on public.kdn28_report_summaries for all using (true) with check (true);

-- ============================================================================
-- kdn29  게시판 (profiles, posts, comments) + 가입 자동 프로필 트리거
-- ============================================================================
drop trigger if exists kdn29_on_auth_user_created on auth.users;
drop table if exists public.kdn29_comments cascade;
drop table if exists public.kdn29_posts cascade;
drop table if exists public.kdn29_profiles cascade;
create table public.kdn29_profiles (
  id uuid primary key references auth.users(id) on delete cascade, email text not null
);
alter table public.kdn29_profiles enable row level security;
create policy "kdn29 prof read" on public.kdn29_profiles for select using (true);
create policy "kdn29 prof ins"  on public.kdn29_profiles for insert with check (auth.uid()=id);
create policy "kdn29 prof upd"  on public.kdn29_profiles for update using (auth.uid()=id);
create or replace function public.kdn29_handle_new_user()
returns trigger language plpgsql security definer as $$
begin
  insert into public.kdn29_profiles (id,email) values (new.id,new.email) on conflict (id) do nothing;
  return new;
end; $$;
create trigger kdn29_on_auth_user_created after insert on auth.users
  for each row execute procedure public.kdn29_handle_new_user();
create table public.kdn29_posts (
  id uuid primary key default gen_random_uuid(),
  title text not null, content text not null,
  author_id uuid not null references public.kdn29_profiles(id) on delete cascade,
  is_notice boolean not null default false, created_at timestamptz not null default now()
);
alter table public.kdn29_posts enable row level security;
create policy "kdn29 posts read" on public.kdn29_posts for select using (true);
create policy "kdn29 posts ins"  on public.kdn29_posts for insert with check (auth.uid()=author_id);
create policy "kdn29 posts upd"  on public.kdn29_posts for update using (auth.uid()=author_id);
create policy "kdn29 posts del"  on public.kdn29_posts for delete using (auth.uid()=author_id);
create table public.kdn29_comments (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.kdn29_posts(id) on delete cascade,
  content text not null,
  author_id uuid not null references public.kdn29_profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);
alter table public.kdn29_comments enable row level security;
create policy "kdn29 cmt read" on public.kdn29_comments for select using (true);
create policy "kdn29 cmt ins"  on public.kdn29_comments for insert with check (auth.uid()=author_id);
create policy "kdn29 cmt del"  on public.kdn29_comments for delete using (auth.uid()=author_id);

-- ============================================================================
-- 완료. 생성된 kdnNN_ 테이블 확인:
--   select table_name from information_schema.tables
--   where table_schema='public' and table_name like 'kdn%' order by table_name;
-- ============================================================================
